# Generated by Django 4.2.5 on 2023-09-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_amplitude', models.IntegerField(choices=[(0, '0 (Additive)'), (1, '1 (Multiplicative)')])),
                ('cycle_frequency', models.FloatField()),
                ('frequency', models.CharField(max_length=4)),
                ('noise_level', models.IntegerField()),
                ('trend_coefficient', models.JSONField(blank=True, default=[0, 0, 0], max_length=3, null=True)),
                ('missing_percentage', models.FloatField(default=0)),
                ('outlier_presentation', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('statr_data', models.DateTimeField()),
                ('end_data', models.DateTimeField()),
                ('series_type', models.CharField(choices=[('multiplicative', 'multiplicative'), ('additive', 'additive')], max_length=15)),
                ('use_case', models.CharField(max_length=400)),
                ('meta_data', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_type', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=7)),
                ('amplitude', models.FloatField(default=0)),
                ('phase_shift', models.FloatField(default=0)),
                ('frequency_multiplier', models.FloatField(default=1)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulator'),
        ),
    ]
