# Generated by Django 4.2.5 on 2023-09-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0002_alter_dataset_noise_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulator',
            old_name='statr_data',
            new_name='start_data',
        ),
    ]
