# Generated by Django 4.2.5 on 2023-09-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0003_rename_statr_data_simulator_start_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulator',
            old_name='question_text',
            new_name='name',
        ),
    ]
