# Generated by Django 4.2.5 on 2023-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0013_dataset_seasonality_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Submitted', max_length=10),
        ),
    ]
