# Generated by Django 4.2.5 on 2023-09-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0015_rename_producer_id_dataset_simulator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='producer_type',
            field=models.CharField(choices=[('kafka', 'kafka'), ('csv', 'CSV')], default='csv', max_length=10),
        ),
    ]
