# Generated by Django 4.2.5 on 2023-09-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0016_simulator_producer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulator',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='simulator',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
