# Generated by Django 4.2.5 on 2023-11-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "simulator_api",
            "0020_rename_missing_percentage_dataset_missing_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="end_date",
            field=models.DateTimeField(),
        ),
    ]
