# Generated by Django 4.2.5 on 2023-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulator_api", "0021_alter_simulator_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulator",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="simulator",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
